
import { SidebarInset, SidebarProvider } from '@/components/ui/sidebar';
import { Metadata } from 'next';
import { AppSidebar } from './utils/app-sidebar';
import { SiteHeader } from './utils/site-header';



export const metadata: Metadata = {
  title: "Univercity Managment",
  description: "Generated by create next app",
};


const DashboardLayout = ({children}: {children: React.ReactNode}) => {
  return (
    <SidebarProvider>
        <AppSidebar/>
        <SidebarInset>
            <SiteHeader/>
            <div className="p-4 pt-4 min-h-screen">{children}</div>
      </SidebarInset>
    </SidebarProvider>
  )
}

export default DashboardLayout